export const mystudydata = [
  { studyId: 1, pofileUrl: '/img/', studyName: '코딩테스트 기초반', type: '정규', memberCount: 1, owner: '바보신', createdTime: '2024-09-10-24:00'},
  { studyId: 2, pofileUrl: '/img/', studyName: '코딩테스트 기초반', type: '자율', memberCount: 1, owner: '바보신', createdTime: '2024-09-10-24:00'},
  
];

export const applystudydata = [
  { studyId: 1, pofileUrl: '/img/', studyName: '코딩테스트 기초반', type: '정규', memberCount: 1, owner: '바보신', createdTime: '2024-09-10-24:00'},
  { studyId: 2, pofileUrl: '/img/', studyName: '코딩테스트 기초반', type: '자율', memberCount: 1, owner: '바보신', createdTime: '2024-09-10-24:00'},
  
];

export const myinfodata = [
  { userId: 1, profileUrl: '/img/', email: 'gtj556@kau.kr', password: "1234", name: '민중갓', grade: 4, major: '소프트웨어학과', handle: '킹갓제너럴GTA', phoneNumber:'010-0000-0000'}
];

export const dummyData = [
  {
    "boardId": 1,
    "type": "공지사항",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": true,
    "fix": true, // 고정된 공지사항
  },
  {
    "boardId": 2,
    "type": "공지사항",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 3,
    "type": "자유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": true,
    "fix": false,
  },
  {
    "boardId": 4,
    "type": "자유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": true,
    "fix": false,
  },
  {
    "boardId": 1115,
    "type": "자유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 6,
    "type": "질문",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": true,
    "fix": false,
  },
  {
    "boardId": 7,
    "type": "질문",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 8,
    "type": "질문",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 9,
    "type": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 10,
    "type": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 11,
    "type": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 12,
    "type": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 13,
    "type": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 14,
    "type": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 15,
    "type": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 16,
    "type": "홍보",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 17,
    "type": "홍보",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 18,
    "type": "홍보",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 19,
    "type": "홍보",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  },
  {
    "boardId": 20,
    "type": "홍보",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "createdTime": "2024.08.31",
    "viewCount": 20,
    "newBoardYn": false,
    "fix": false,
  }
];
