// export const mystudydata = [
//   { studyId: 1, pofileUrl: '/img/', studyName: '코딩테스트 기초반', category: '정규', memberCount: 1, owner: '바보신', createdTime: '2024-09-10-24:00'},
//   "deleteYn": false,
//   "saveYn": false,
//   { studyId: 2, pofileUrl: '/img/', studyName: '코딩테스트 기초반', category: '자율', memberCount: 1, owner: '바보신', createdTime: '2024-09-10-24:00'},
//   "deleteYn": false,
//   "saveYn": false,
  
// ];

// export const applystudydata = [
//   { studyId: 1, pofileUrl: '/img/', studyName: '코딩테스트 기초반', category: '정규', memberCount: 1, owner: '바보신', createdTime: '2024-09-10-24:00'},
//   "deleteYn": false,
//   "saveYn": false,
//   { studyId: 2, pofileUrl: '/img/', studyName: '코딩테스트 기초반', category: '자율', memberCount: 1, owner: '바보신', createdTime: '2024-09-10-24:00'},
//   "deleteYn": false,
//   "saveYn": false,
  
// ];

// export const myinfodata = [
//   { userId: 1, profileUrl: '/img/', email: 'gtj556@kau.kr', password: "1234", name: '민중갓', grade: 4, major: '소프트웨어학과', handle: '킹갓제너럴GTA', phoneNumber:'010-0000-0000'}
// ];

export const dummyData = [
  {
    "boardId": 1,
    "category": "공지사항",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": true,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": true,
    "fixYn": true, // 고정된 공지사항
  },
  {
    "boardId": 2,
    "category": "공지사항",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 3,
    "category": "자유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": true,
    "fixYn": false,
  },
  {
    "boardId": 4,
    "category": "자유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": true,
    "fixYn": false,
  },
  {
    "boardId": 1115,
    "category": "자유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 6,
    "category": "질문",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": true,
    "fixYn": false,
  },
  {
    "boardId": 7,
    "category": "질문",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 8,
    "category": "질문",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 9,
    "category": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 10,
    "category": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 11,
    "category": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 12,
    "category": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 13,
    "category": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 14,
    "category": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 15,
    "category": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 16,
    "category": "홍보",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 17,
    "category": "홍보",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 18,
    "category": "홍보",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 19,
    "category": "홍보",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  },
  {
    "boardId": 20,
    "category": "홍보",
    "title": 'last다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "createdName": "이유경",
    "createdTime": "2024-10-18T09:15:30",
    "deleteYn": false,
    "saveYn": false,
    "viewCount": 20,
    "newBoardYn": false,
    "fixYn": false,
  }
];
