export const dummyData = [
  {
    "postId": 1,
    "type": "공지사항",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": true,
    "fix": true, // 고정된 공지사항
  },
  {
    "postId": 2,
    "type": "공지사항",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 3,
    "type": "자유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": true,
    "fix": false,
  },
  {
    "postId": 4,
    "type": "자유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": true,
    "fix": false,
  },
  {
    "postId": 1115,
    "type": "자유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 6,
    "type": "질문",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": true,
    "fix": false,
  },
  {
    "postId": 7,
    "type": "질문",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 8,
    "type": "질문",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 9,
    "type": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 10,
    "type": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 11,
    "type": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 12,
    "type": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 13,
    "type": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 14,
    "type": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 15,
    "type": "정보 공유",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 16,
    "type": "홍보",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 17,
    "type": "홍보",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 18,
    "type": "홍보",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 19,
    "type": "홍보",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  },
  {
    "postId": 20,
    "type": "홍보",
    "title": '다양한 예제로 쉽게 배우는 오라클 SQL과 PL/SQL, 불친절한 SQL 프로그래밍',
    "writer": "이유경",
    "date": "2024.08.31",
    "view": 20,
    "new": false,
    "fix": false,
  }
];
